apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: us-central1-docker.pkg.dev/ms-gcp-ser-sandbox/gcp-easy-dashboard/frontend:v1
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: regcred
